name: Run Telegram Bot
on:
  workflow_dispatch:    # Pwede i-run manually
  schedule:
    - cron: '*/5 * * * *'  # Auto-restart every 5 mins
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install python-telegram-bot
      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python bot.py
